 api_token: token
 api_secret: secret
 base_mmp_url: http://
 mmp_websocket_url: ws://
 base_url: http://
 partner: catpoc
 domain: testctx
 context: testctx
 catapult_user_id: user
 catapult_api_token: token
 catapult_api_secret: secret
