 api_token: token
 api_secret: secret
 base_mmp_url: http://api-stage.bwmsg.io
 partner: catpoc
 domain: testctx
 context: testctx
 catapult_user_id: user
 catapult_api_token: token
 catapult_api_secret: secret
